In [11]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

STEP 1: Loading the csv file

In [ ]:
df = pd.read_csv('spam.csv', encoding = 'latin-1')  # load the data

In [4]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In RAG, we do not segregate input and output.

In [5]:
x = df['v2']
y = df['v1']

### Vectorization
#### Since the model cannot understand text, it will only understand numbers, we need to use vectorization

In [ ]:
vectors = CountVectorizer(stop_words='english') # acts as embedding model

In [ ]:
model = KNeighborsClassifier() # acts as vector database, stores the vectors
# model.fit(x,y)  # will give error
# ValueError: Expected a 2-dimensional container but got <class 'pandas.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [22]:
vectors.fit_transform(x) # returns sparse matrix
values = vectors.fit_transform(x).toarray()  # converted sentences into vectors

cols = vectors.get_feature_names_out()

updated_x = pd.DataFrame(values, columns = cols)
updated_x

,00,000,000pes,008704050406,0089,0121,01223585236,01223585334,0125698789,02,...,ó_,û_,û_thanks,ûªm,ûªt,ûªve,ûï,ûïharry,ûò,ûówell
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5567,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5568,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5569,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5570,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5571,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
model.fit(updated_x, y)  # stored the information (input and output)(stores the row vectors)

KNeighborsClassifier()

In [34]:
new_input = [df['v2'][0]]   # here it is not in numbers, the trained model having numbers is comparing with text in new input
new_input  # this is first row

['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...']

In [35]:
# model.predict(new_input)

In [38]:
updated_new_input = vectors.transform(new_input).toarray()
# updated_new_cols = vectors.get_feature_names_out()

In [40]:
model.predict(updated_new_input)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array(['ham'], dtype=object)

Practical test, until saturday, next monday.
- code structure, code quality
- write logic inside class or function
- doc string(triple quotes) must be present inside every function (to store the values)
- define, why you create this function and what it does

Collecting sentence_transformers
  Downloading sentence_transformers-5.6.1-py3-none-any.whl.metadata (18 kB)
Collecting transformers<6.0.0,>=4.41.0 (from sentence_transformers)
  Downloading transformers-5.14.1-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: huggingface-hub>=0.23.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from sentence_transformers) (1.13.0)
Collecting torch>=1.11.0 (from sentence_transformers)
  Downloading torch-2.13.0-cp314-cp314-win_amd64.whl.metadata (39 kB)
Requirement already satisfied: numpy>=1.20.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from sentence_transformers) (2.4.2)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from sentence_transformers) (1.8.0)
Requirement already satisfied: scipy>=1.0.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from sentence_transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from sentence_transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from sentence_transformers) (4.67.3)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (2026.2.28)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<6.0.0,>=4.41.0->sentence_transformers)
  Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: typer in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.25.1)
Collecting safetensors>=0.8.0 (from transformers<6.0.0,>=4.41.0->sentence_transformers)
  Downloading safetensors-0.8.0-cp310-abi3-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: filelock>=3.10.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from huggingface-hub>=0.23.0->sentence_transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from huggingface-hub>=0.23.0->sentence_transformers) (2026.4.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from huggingface-hub>=0.23.0->sentence_transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from huggingface-hub>=0.23.0->sentence_transformers) (0.28.1)
Requirement already satisfied: anyio in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (4.12.1)
Requirement already satisfied: certifi in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (0.16.0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn>=0.22.0->sentence_transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn>=0.22.0->sentence_transformers) (3.6.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from torch>=1.11.0->sentence_transformers) (82.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from torch>=1.11.0->sentence_transformers) (1.14.0)
Collecting networkx>=2.5.1 (from torch>=1.11.0->sentence_transformers)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: jinja2 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from torch>=1.11.0->sentence_transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence_transformers) (1.3.0)
Requirement already satisfied: colorama in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from tqdm>=4.0.0->sentence_transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from jinja2->torch>=1.11.0->sentence_transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence_transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence_transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence_transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence_transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence_transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence_transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence_transformers) (0.1.2)
Downloading sentence_transformers-5.6.1-py3-none-any.whl (596 kB)
   ---------------------------------------- 0.0/596.7 kB ? eta -:--:--
   ----------------- ---------------------- 262.1/596.7 kB ? eta -:--:--
   ---------------------------------------- 596.7/596.7 kB 1.6 MB/s  0:00:00
Downloading transformers-5.14.1-py3-none-any.whl (11.6 MB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.6 MB 7.4 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/11.6 MB 3.4 MB/s eta 0:00:04
   ------ --------------------------------- 1.8/11.6 MB 3.1 MB/s eta 0:00:04
   --------- ------------------------------ 2.6/11.6 MB 3.3 MB/s eta 0:00:03
   ------------ --------------------------- 3.7/11.6 MB 3.7 MB/s eta 0:00:03
   --------------- ------------------------ 4.5/11.6 MB 3.8 MB/s eta 0:00:02
   ---------------- ----------------------- 4.7/11.6 MB 3.5 MB/s eta 0:00:02
   ------------------ --------------------- 5.2/11.6 MB 3.2 MB/s eta 0:00:02
   -------------------- ------------------- 6.0/11.6 MB 3.4 MB/s eta 0:00:02
   ---------------------- ----------------- 6.6/11.6 MB 3.1 MB/s eta 0:00:02
   ---------------------- ----------------- 6.6/11.6 MB 3.1 MB/s eta 0:00:02
   ---------------------- ----------------- 6.6/11.6 MB 3.1 MB/s eta 0:00:02
   ------------------------- -------------- 7.3/11.6 MB 2.7 MB/s eta 0:00:02
   ------------------------- -------------- 7.3/11.6 MB 2.7 MB/s eta 0:00:02
   --------------------------- ------------ 8.1/11.6 MB 2.5 MB/s eta 0:00:02
   ----------------------------- ---------- 8.7/11.6 MB 2.6 MB/s eta 0:00:02
   ------------------------------ --------- 8.9/11.6 MB 2.6 MB/s eta 0:00:02
   --------------------------------- ------ 9.7/11.6 MB 2.5 MB/s eta 0:00:01
   ----------------------------------- ---- 10.2/11.6 MB 2.5 MB/s eta 0:00:01
   ------------------------------------ --- 10.7/11.6 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 11.3/11.6 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 11.6/11.6 MB 2.5 MB/s  0:00:04
Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
Downloading safetensors-0.8.0-cp310-abi3-win_amd64.whl (355 kB)
Downloading torch-2.13.0-cp314-cp314-win_amd64.whl (122.1 MB)
   ---------------------------------------- 0.0/122.1 MB ? eta -:--:--
   ---------------------------------------- 0.8/122.1 MB 3.6 MB/s eta 0:00:34
    --------------------------------------- 1.6/122.1 MB 3.6 MB/s eta 0:00:34
    --------------------------------------- 2.1/122.1 MB 3.4 MB/s eta 0:00:36
   - -------------------------------------- 3.1/122.1 MB 3.6 MB/s eta 0:00:34
   - -------------------------------------- 3.1/122.1 MB 3.6 MB/s eta 0:00:34
   - -------------------------------------- 4.2/122.1 MB 3.3 MB/s eta 0:00:36
   - -------------------------------------- 5.2/122.1 MB 3.5 MB/s eta 0:00:34
   -- ------------------------------------- 6.3/122.1 MB 3.6 MB/s eta 0:00:33
   -- ------------------------------------- 7.1/122.1 MB 3.7 MB/s eta 0:00:31
   -- ------------------------------------- 7.6/122.1 MB 3.5 MB/s eta 0:00:33
   -- ------------------------------------- 8.1/122.1 MB 3.4 MB/s eta 0:00:34
   -- ------------------------------------- 8.9/122.1 MB 3.4 MB/s eta 0:00:33
   --- ------------------------------------ 9.4/122.1 MB 3.4 MB/s eta 0:00:33
   --- ------------------------------------ 10.2/122.1 MB 3.4 MB/s eta 0:00:33
   --- ------------------------------------ 10.7/122.1 MB 3.3 MB/s eta 0:00:34
   --- ------------------------------------ 11.3/122.1 MB 3.3 MB/s eta 0:00:34
   ---- ----------------------------------- 12.3/122.1 MB 3.3 MB/s eta 0:00:33
   ---- ----------------------------------- 13.1/122.1 MB 3.4 MB/s eta 0:00:33
   ---- ----------------------------------- 13.6/122.1 MB 3.3 MB/s eta 0:00:33
   ---- ----------------------------------- 14.4/122.1 MB 3.3 MB/s eta 0:00:33
   ---- ----------------------------------- 15.2/122.1 MB 3.4 MB/s eta 0:00:32
   ----- ---------------------------------- 15.7/122.1 MB 3.3 MB/s eta 0:00:33
   ----- ---------------------------------- 16.3/122.1 MB 3.3 MB/s eta 0:00:33
   ----- ---------------------------------- 16.5/122.1 MB 3.3 MB/s eta 0:00:33
   ----- ---------------------------------- 17.3/122.1 MB 3.2 MB/s eta 0:00:33
   ----- ---------------------------------- 17.8/122.1 MB 3.2 MB/s eta 0:00:33
   ------ --------------------------------- 18.6/122.1 MB 3.2 MB/s eta 0:00:32
   ------ --------------------------------- 18.6/122.1 MB 3.2 MB/s eta 0:00:32
   ------ --------------------------------- 19.4/122.1 MB 3.1 MB/s eta 0:00:34
   ------ --------------------------------- 19.9/122.1 MB 3.1 MB/s eta 0:00:34
   ------ --------------------------------- 20.7/122.1 MB 3.1 MB/s eta 0:00:33
   ------ --------------------------------- 21.2/122.1 MB 3.1 MB/s eta 0:00:33
   ------- -------------------------------- 21.5/122.1 MB 3.1 MB/s eta 0:00:33
   ------- -------------------------------- 22.3/122.1 MB 3.0 MB/s eta 0:00:34
   ------- -------------------------------- 23.3/122.1 MB 3.1 MB/s eta 0:00:33
   ------- -------------------------------- 24.4/122.1 MB 3.1 MB/s eta 0:00:32
   -------- ------------------------------- 24.9/122.1 MB 3.1 MB/s eta 0:00:32
   -------- ------------------------------- 26.0/122.1 MB 3.1 MB/s eta 0:00:31
   -------- ------------------------------- 26.5/122.1 MB 3.2 MB/s eta 0:00:30
   -------- ------------------------------- 26.7/122.1 MB 3.1 MB/s eta 0:00:31
   -------- ------------------------------- 27.3/122.1 MB 3.1 MB/s eta 0:00:31
   --------- ------------------------------ 28.0/122.1 MB 3.1 MB/s eta 0:00:31
   --------- ------------------------------ 28.8/122.1 MB 3.1 MB/s eta 0:00:30
   --------- ------------------------------ 30.1/122.1 MB 3.2 MB/s eta 0:00:29
   ---------- ----------------------------- 31.2/122.1 MB 3.2 MB/s eta 0:00:29
   ---------- ----------------------------- 32.0/122.1 MB 3.2 MB/s eta 0:00:28
   ---------- ----------------------------- 33.0/122.1 MB 3.3 MB/s eta 0:00:28
   ----------- ---------------------------- 33.8/122.1 MB 3.3 MB/s eta 0:00:27
   ----------- ---------------------------- 34.6/122.1 MB 3.3 MB/s eta 0:00:27
   ----------- ---------------------------- 35.1/122.1 MB 3.3 MB/s eta 0:00:27
   ----------- ---------------------------- 35.9/122.1 MB 3.3 MB/s eta 0:00:27
   ----------- ---------------------------- 36.4/122.1 MB 3.3 MB/s eta 0:00:27
   ------------ --------------------------- 37.0/122.1 MB 3.2 MB/s eta 0:00:27
   ------------ --------------------------- 37.7/122.1 MB 3.2 MB/s eta 0:00:27
   ------------ --------------------------- 38.8/122.1 MB 3.3 MB/s eta 0:00:26
   ------------ --------------------------- 39.6/122.1 MB 3.3 MB/s eta 0:00:26
   ------------- -------------------------- 40.1/122.1 MB 3.3 MB/s eta 0:00:25
   ------------- -------------------------- 41.2/122.1 MB 3.3 MB/s eta 0:00:25
   ------------- -------------------------- 41.9/122.1 MB 3.3 MB/s eta 0:00:25
   -------------- ------------------------- 43.0/122.1 MB 3.3 MB/s eta 0:00:24
   -------------- ------------------------- 43.8/122.1 MB 3.3 MB/s eta 0:00:24
   -------------- ------------------------- 44.3/122.1 MB 3.3 MB/s eta 0:00:24
   -------------- ------------------------- 44.3/122.1 MB 3.3 MB/s eta 0:00:24
   -------------- ------------------------- 45.1/122.1 MB 3.3 MB/s eta 0:00:24
   --------------- ------------------------ 46.1/122.1 MB 3.3 MB/s eta 0:00:24
   --------------- ------------------------ 46.7/122.1 MB 3.3 MB/s eta 0:00:23
   --------------- ------------------------ 47.4/122.1 MB 3.3 MB/s eta 0:00:23
   --------------- ------------------------ 48.2/122.1 MB 3.3 MB/s eta 0:00:23
   ---------------- ----------------------- 49.5/122.1 MB 3.3 MB/s eta 0:00:22
   ---------------- ----------------------- 50.1/122.1 MB 3.3 MB/s eta 0:00:22
   ---------------- ----------------------- 50.6/122.1 MB 3.3 MB/s eta 0:00:22
   ---------------- ----------------------- 51.4/122.1 MB 3.3 MB/s eta 0:00:22
   ----------------- ---------------------- 51.9/122.1 MB 3.3 MB/s eta 0:00:22
   ----------------- ---------------------- 52.7/122.1 MB 3.3 MB/s eta 0:00:22
   ----------------- ---------------------- 53.5/122.1 MB 3.3 MB/s eta 0:00:21
   ----------------- ---------------------- 54.8/122.1 MB 3.3 MB/s eta 0:00:21
   ------------------ --------------------- 55.6/122.1 MB 3.3 MB/s eta 0:00:20
   ------------------ --------------------- 55.8/122.1 MB 3.3 MB/s eta 0:00:20
   ------------------ --------------------- 56.4/122.1 MB 3.3 MB/s eta 0:00:20
   ------------------ --------------------- 56.6/122.1 MB 3.3 MB/s eta 0:00:20
   ------------------ --------------------- 57.4/122.1 MB 3.3 MB/s eta 0:00:20
   ------------------ --------------------- 57.9/122.1 MB 3.3 MB/s eta 0:00:20
   ------------------- -------------------- 58.2/122.1 MB 3.3 MB/s eta 0:00:20
   ------------------- -------------------- 58.7/122.1 MB 3.3 MB/s eta 0:00:20
   ------------------- -------------------- 59.5/122.1 MB 3.3 MB/s eta 0:00:20
   ------------------- -------------------- 59.8/122.1 MB 3.2 MB/s eta 0:00:20
   ------------------- -------------------- 60.3/122.1 MB 3.2 MB/s eta 0:00:20
   -------------------- ------------------- 61.1/122.1 MB 3.2 MB/s eta 0:00:19
   -------------------- ------------------- 61.9/122.1 MB 3.2 MB/s eta 0:00:19
   -------------------- ------------------- 62.7/122.1 MB 3.2 MB/s eta 0:00:19
   -------------------- ------------------- 63.4/122.1 MB 3.2 MB/s eta 0:00:19
   --------------------- ------------------ 64.2/122.1 MB 3.2 MB/s eta 0:00:18
   --------------------- ------------------ 64.5/122.1 MB 3.2 MB/s eta 0:00:18
   --------------------- ------------------ 65.3/122.1 MB 3.2 MB/s eta 0:00:18
   --------------------- ------------------ 65.5/122.1 MB 3.2 MB/s eta 0:00:18
   --------------------- ------------------ 66.1/122.1 MB 3.2 MB/s eta 0:00:18
   --------------------- ------------------ 66.8/122.1 MB 3.2 MB/s eta 0:00:18
   ---------------------- ----------------- 67.6/122.1 MB 3.2 MB/s eta 0:00:18
   ---------------------- ----------------- 68.9/122.1 MB 3.2 MB/s eta 0:00:17
   ---------------------- ----------------- 69.5/122.1 MB 3.2 MB/s eta 0:00:17
   ----------------------- ---------------- 70.3/122.1 MB 3.2 MB/s eta 0:00:17
   ----------------------- ---------------- 71.0/122.1 MB 3.2 MB/s eta 0:00:16
   ----------------------- ---------------- 71.6/122.1 MB 3.2 MB/s eta 0:00:16
   ----------------------- ---------------- 72.9/122.1 MB 3.3 MB/s eta 0:00:16
   ----------------------- ---------------- 73.1/122.1 MB 3.3 MB/s eta 0:00:16
   ------------------------ --------------- 74.4/122.1 MB 3.3 MB/s eta 0:00:15
   ------------------------ --------------- 74.7/122.1 MB 3.3 MB/s eta 0:00:15
   ------------------------ --------------- 74.7/122.1 MB 3.3 MB/s eta 0:00:15
   ------------------------ --------------- 75.0/122.1 MB 3.2 MB/s eta 0:00:15
   ------------------------ --------------- 75.0/122.1 MB 3.2 MB/s eta 0:00:15
   ------------------------ --------------- 75.2/122.1 MB 3.2 MB/s eta 0:00:15
   ------------------------- -------------- 76.3/122.1 MB 3.2 MB/s eta 0:00:15
   ------------------------- -------------- 77.1/122.1 MB 3.2 MB/s eta 0:00:15
   ------------------------- -------------- 77.9/122.1 MB 3.2 MB/s eta 0:00:14
   ------------------------- -------------- 78.6/122.1 MB 3.2 MB/s eta 0:00:14
   ------------------------- -------------- 79.2/122.1 MB 3.2 MB/s eta 0:00:14
   -------------------------- ------------- 79.4/122.1 MB 3.2 MB/s eta 0:00:14
   -------------------------- ------------- 80.5/122.1 MB 3.2 MB/s eta 0:00:14
   -------------------------- ------------- 81.5/122.1 MB 3.2 MB/s eta 0:00:13
   -------------------------- ------------- 82.1/122.1 MB 3.2 MB/s eta 0:00:13
   --------------------------- ------------ 82.6/122.1 MB 3.2 MB/s eta 0:00:13
   --------------------------- ------------ 83.1/122.1 MB 3.2 MB/s eta 0:00:13
   --------------------------- ------------ 83.9/122.1 MB 3.2 MB/s eta 0:00:13
   --------------------------- ------------ 84.7/122.1 MB 3.2 MB/s eta 0:00:12
   ---------------------------- ----------- 85.7/122.1 MB 3.2 MB/s eta 0:00:12
   ---------------------------- ----------- 86.2/122.1 MB 3.2 MB/s eta 0:00:12
   ---------------------------- ----------- 87.0/122.1 MB 3.2 MB/s eta 0:00:12
   ---------------------------- ----------- 87.6/122.1 MB 3.2 MB/s eta 0:00:11
   ----------------------------- ---------- 88.6/122.1 MB 3.2 MB/s eta 0:00:11
   ----------------------------- ---------- 89.1/122.1 MB 3.2 MB/s eta 0:00:11
   ----------------------------- ---------- 89.7/122.1 MB 3.2 MB/s eta 0:00:11

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\Users\\LENOVO\\AppData\\Local\\Programs\\Python\\Python314\\Lib\\site-packages\\transformers\\models\\esm\\openfold_utils\\feats.py'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip